/* AUTO-GENERATED by tests/gen_cvxpy_refs.py - do not edit. */
/* Reference solutions from cvxpy (CLARABEL). */
#ifndef VSOLVER_CVXPY_REFS_H
#define VSOLVER_CVXPY_REFS_H

typedef struct {
    const char *name; int n, m, ncones;
    const int *Pi, *Pj; const double *Px; int Pnnz;
    const double *q;
    const int *Ai, *Aj; const double *Ax; int Annz;
    const double *b;
    const int *cone_type, *cone_dim;
    const double *refx; double refobj;
} cvxpy_case;

/* lp_inequality: pobj=-5 */
static const int c0_Pi[] = {0};
static const int c0_Pj[] = {0};
static const double c0_Px[] = {0};
static const double c0_q[] = {-1, -2};
static const int c0_Ai[] = {0, 0, 1, 1, 2, 3};
static const int c0_Aj[] = {0, 1, 0, 1, 0, 1};
static const double c0_Ax[] = {1, 1, 1, 3, -1, -1};
static const double c0_b[] = {4, 6, 0, 0};
static const int c0_ct[] = {1};
static const int c0_cd[] = {4};
static const double c0_refx[] = {2.9999999999959455, 0.99999999993664235};

/* lp_equality: pobj=1.000000003 */
static const int c1_Pi[] = {0};
static const int c1_Pj[] = {0};
static const double c1_Px[] = {0};
static const double c1_q[] = {2, 3, 1};
static const int c1_Ai[] = {0, 0, 0, 1, 2, 3};
static const int c1_Aj[] = {0, 1, 2, 0, 1, 2};
static const double c1_Ax[] = {1, 1, 1, -1, -1, -1};
static const double c1_b[] = {1, 0, 0, 0};
static const int c1_ct[] = {0, 1};
static const int c1_cd[] = {1, 3};
static const double c1_refx[] = {1.5622350233356556e-09, 5.3298728073505494e-10, 0.99999999790478311};

/* qp_dense_bounds: pobj=-1.999999995 */
static const int c2_Pi[] = {0, 0, 1};
static const int c2_Pj[] = {0, 1, 1};
static const double c2_Px[] = {2, 0.5, 1};
static const double c2_q[] = {-1, -2};
static const int c2_Ai[] = {0, 1};
static const int c2_Aj[] = {0, 1};
static const double c2_Ax[] = {-1, -1};
static const double c2_b[] = {0, 0};
static const int c2_ct[] = {1};
static const int c2_cd[] = {2};
static const double c2_refx[] = {7.493375344532773e-05, 1.9999625343584688};

/* qp_equality: pobj=0.1666666667 */
static const int c3_Pi[] = {0, 1, 2};
static const int c3_Pj[] = {0, 1, 2};
static const double c3_Px[] = {1, 1, 1};
static const double c3_q[] = {0, 0, 0};
static const int c3_Ai[] = {0, 0, 0};
static const int c3_Aj[] = {0, 1, 2};
static const double c3_Ax[] = {1, 1, 1};
static const double c3_b[] = {1};
static const int c3_ct[] = {0};
static const int c3_cd[] = {1};
static const double c3_refx[] = {0.33333333333333331, 0.33333333333333331, 0.33333333333333331};

/* socp_ball: pobj=-2.236067974 */
static const int c4_Pi[] = {0};
static const int c4_Pj[] = {0};
static const double c4_Px[] = {0};
static const double c4_q[] = {1, 2};
static const int c4_Ai[] = {1, 2};
static const int c4_Aj[] = {0, 1};
static const double c4_Ax[] = {-1, -1};
static const double c4_b[] = {1, 0, 0};
static const int c4_ct[] = {2};
static const int c4_cd[] = {3};
static const double c4_refx[] = {-0.44721359477393891, -0.89442718954787781};

/* socp_ball_proj: pobj=-2.328427122 */
static const int c5_Pi[] = {0, 1};
static const int c5_Pj[] = {0, 1};
static const double c5_Px[] = {1, 1};
static const double c5_q[] = {-2, -2};
static const int c5_Ai[] = {1, 2};
static const int c5_Aj[] = {0, 1};
static const double c5_Ax[] = {-1, -1};
static const double c5_b[] = {1, 0, 0};
static const int c5_ct[] = {2};
static const int c5_cd[] = {3};
static const double c5_refx[] = {0.70710678026852514, 0.70710678026852514};

/* socp_nonneg_mix: pobj=-1.414213563 */
static const int c6_Pi[] = {0};
static const int c6_Pj[] = {0};
static const double c6_Px[] = {0};
static const double c6_q[] = {-1, -1};
static const int c6_Ai[] = {0, 1, 3, 4};
static const int c6_Aj[] = {0, 1, 0, 1};
static const double c6_Ax[] = {-1, -1, -1, -1};
static const double c6_b[] = {0, 0, 1, 0, 0};
static const int c6_ct[] = {1, 2};
static const int c6_cd[] = {2, 3};
static const double c6_refx[] = {0.70710678161622065, 0.70710678161622054};

/* qp_simplex: pobj=-1.499999997 */
static const int c7_Pi[] = {0, 1, 2};
static const int c7_Pj[] = {0, 1, 2};
static const double c7_Px[] = {1, 1, 1};
static const double c7_q[] = {-2, -1, 0};
static const int c7_Ai[] = {0, 0, 0, 1, 2, 3};
static const int c7_Aj[] = {0, 1, 2, 0, 1, 2};
static const double c7_Ax[] = {1, 1, 1, -1, -1, -1};
static const double c7_b[] = {1, 0, 0, 0};
static const int c7_ct[] = {0, 1};
static const int c7_cd[] = {1, 3};
static const double c7_refx[] = {0.99995237111072133, 4.7628048720670509e-05, 8.4016123284404415e-10};

/* socp_two_blocks: pobj=-3.650281526 */
static const int c8_Pi[] = {0};
static const int c8_Pj[] = {0};
static const double c8_Px[] = {0};
static const double c8_q[] = {-1, -1, -1, -2};
static const int c8_Ai[] = {1, 2, 4, 5};
static const int c8_Aj[] = {0, 1, 2, 3};
static const double c8_Ax[] = {-1, -1, -1, -1};
static const double c8_b[] = {1, 0, 0, 1, 0, 0};
static const int c8_ct[] = {2, 2};
static const int c8_cd[] = {3, 3};
static const double c8_refx[] = {0.70710677758700546, 0.70710677758700546, 0.44721359420933826, 0.89442718841867652};

/* qp_random_box: pobj=-1.426185558 */
static const int c9_Pi[] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4};
static const int c9_Pj[] = {0, 1, 2, 3, 4, 1, 2, 3, 4, 2, 3, 4, 3, 4, 4};
static const double c9_Px[] = {6.0987441190968861, -0.38611652532353091, 0.73839816195177832, -1.7903063592303465, -0.58490996890654923, 3.0824150747508732, 0.94942807807077545, 1.8641440520515817, 1.512976539536288, 4.6982734001276274, 0.012614100258026398, -0.31857182419912689, 6.58942412109137, 3.2317652246540152, 3.2800487788002788};
static const double c9_q[] = {-0.18693094462995438, -2.5167597108205131, -0.5386928958466366, -0.048500945401071985, 0.11330898600330756};
static const int c9_Ai[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const int c9_Aj[] = {0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const double c9_Ax[] = {1, 1, 1, 1, 1, -1, -1, -1, -1, -1};
static const double c9_b[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static const int c9_ct[] = {1};
static const int c9_cd[] = {10};
static const double c9_refx[] = {0.055558748370668314, 0.99999999393274375, -0.12781867096650101, -0.030575333708143599, -0.46819296905668117};

/* qp_box_equality: pobj=-0.2499999966 */
static const int c10_Pi[] = {0, 1, 2};
static const int c10_Pj[] = {0, 1, 2};
static const double c10_Px[] = {1, 1, 1};
static const double c10_q[] = {-1, 0, 1};
static const int c10_Ai[] = {0, 0, 0, 1, 2, 3, 4, 5, 6};
static const int c10_Aj[] = {0, 1, 2, 0, 1, 2, 0, 1, 2};
static const double c10_Ax[] = {1, 1, 1, 1, 1, 1, -1, -1, -1};
static const double c10_b[] = {1, 0.5, 0.5, 0.5, 0, 0, 0};
static const int c10_ct[] = {0, 1};
static const int c10_cd[] = {1, 6};
static const double c10_refx[] = {0.49999999930474576, 0.49999999530767147, 5.3875834206713944e-09};

/* socp_robust_lp: pobj=-1.47759225 */
static const int c11_Pi[] = {0};
static const int c11_Pj[] = {0};
static const double c11_Px[] = {0};
static const double c11_q[] = {-1, -1};
static const int c11_Ai[] = {0, 1, 2, 2, 3, 4};
static const int c11_Aj[] = {0, 1, 0, 1, 0, 1};
static const double c11_Ax[] = {-1, -1, 1, 1, -0.5, -0.5};
static const double c11_b[] = {0, 0, 2, 0, 0};
static const int c11_ct[] = {1, 2};
static const int c11_cd[] = {2, 3};
static const double c11_refx[] = {0.73879612498990199, 0.7387961249899021};

/* socp_ball4d: pobj=-7.499999989 */
static const int c12_Pi[] = {0};
static const int c12_Pj[] = {0};
static const double c12_Px[] = {0};
static const double c12_q[] = {1, -2, 0.5, 1};
static const int c12_Ai[] = {1, 2, 3, 4};
static const int c12_Aj[] = {0, 1, 2, 3};
static const double c12_Ax[] = {-1, -1, -1, -1};
static const double c12_b[] = {3, 0, 0, 0, 0};
static const int c12_ct[] = {2};
static const int c12_cd[] = {5};
static const double c12_refx[] = {-1.1999999982401504, 2.3999999964803007, -0.59999999912007518, -1.1999999982401504};

static const cvxpy_case cvxpy_cases[] = {
  {"lp_inequality", 2, 4, 1, c0_Pi, c0_Pj, c0_Px, 0, c0_q, c0_Ai, c0_Aj, c0_Ax, 6, c0_b, c0_ct, c0_cd, c0_refx, -4.9999999998692299},
  {"lp_equality", 3, 4, 2, c1_Pi, c1_Pj, c1_Px, 0, c1_q, c1_Ai, c1_Aj, c1_Ax, 6, c1_b, c1_ct, c1_cd, c1_refx, 1.000000002628215},
  {"qp_dense_bounds", 2, 2, 1, c2_Pi, c2_Pj, c2_Px, 3, c2_q, c2_Ai, c2_Aj, c2_Ax, 2, c2_b, c2_ct, c2_cd, c2_refx, -1.9999999950868159},
  {"qp_equality", 3, 1, 1, c3_Pi, c3_Pj, c3_Px, 3, c3_q, c3_Ai, c3_Aj, c3_Ax, 3, c3_b, c3_ct, c3_cd, c3_refx, 0.16666666666666666},
  {"socp_ball", 2, 3, 1, c4_Pi, c4_Pj, c4_Px, 0, c4_q, c4_Ai, c4_Aj, c4_Ax, 2, c4_b, c4_ct, c4_cd, c4_refx, -2.2360679738696945},
  {"socp_ball_proj", 2, 3, 1, c5_Pi, c5_Pj, c5_Px, 2, c5_q, c5_Ai, c5_Aj, c5_Ax, 2, c5_b, c5_ct, c5_cd, c5_refx, -2.3284271223723803},
  {"socp_nonneg_mix", 2, 5, 2, c6_Pi, c6_Pj, c6_Px, 0, c6_q, c6_Ai, c6_Aj, c6_Ax, 4, c6_b, c6_ct, c6_cd, c6_refx, -1.4142135632324413},
  {"qp_simplex", 3, 4, 2, c7_Pi, c7_Pj, c7_Px, 3, c7_q, c7_Ai, c7_Aj, c7_Ax, 6, c7_b, c7_ct, c7_cd, c7_refx, -1.499999996890971},
  {"socp_two_blocks", 4, 6, 2, c8_Pi, c8_Pj, c8_Px, 0, c8_q, c8_Ai, c8_Aj, c8_Ax, 4, c8_b, c8_ct, c8_cd, c8_refx, -3.6502815262207022},
  {"qp_random_box", 5, 10, 1, c9_Pi, c9_Pj, c9_Px, 15, c9_q, c9_Ai, c9_Aj, c9_Ax, 10, c9_b, c9_ct, c9_cd, c9_refx, -1.4261855583639194},
  {"qp_box_equality", 3, 7, 2, c10_Pi, c10_Pj, c10_Px, 3, c10_q, c10_Ai, c10_Aj, c10_Ax, 9, c10_b, c10_ct, c10_cd, c10_refx, -0.24999999661095365},
  {"socp_robust_lp", 2, 5, 2, c11_Pi, c11_Pj, c11_Px, 0, c11_q, c11_Ai, c11_Aj, c11_Ax, 6, c11_b, c11_ct, c11_cd, c11_refx, -1.477592249979804},
  {"socp_ball4d", 4, 5, 1, c12_Pi, c12_Pj, c12_Px, 0, c12_q, c12_Ai, c12_Aj, c12_Ax, 4, c12_b, c12_ct, c12_cd, c12_refx, -7.4999999890009397},
};
enum { cvxpy_ncases = sizeof(cvxpy_cases)/sizeof(cvxpy_cases[0]) };

#endif
